name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: "Fullstack/Part 11/fullstack-pipeline-app/backend"

      - name: Lint
        run: npm run lint
        working-directory: "Fullstack/Part 11/fullstack-pipeline-app/backend"

      - name: Build
        run: npm run build
        working-directory: "Fullstack/Part 11/fullstack-pipeline-app/backend"

      - name: Run unit tests
        run: npm test
        working-directory: "Fullstack/Part 11/fullstack-pipeline-app/backend"

      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: "Fullstack/Part 11/fullstack-pipeline-app/backend"

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: echo "🚀 Deploying to production..."

